"""added rating column

Revision ID: 77311a70c424
Revises: 718137a8a739
Create Date: 2025-03-27 05:14:34.221565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77311a70c424'
down_revision: Union[str, None] = '718137a8a739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rating', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_rating'), 'users', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_rating'), table_name='users')
    op.drop_column('users', 'rating')
    # ### end Alembic commands ###
